const help = [
	"Hello there, I couldn't help but notice you seem burdened… Want to talk about it?",
	"Why bother fixing anything when you can just walk away now?",
	"Hey, come in, sit—tell me what’s weighing on your heart.",
	"If you think this marriage will magically fix itself, you're delusional.",
	"You’re safe here. Start wherever you need to.",
	"Your partner saw your weaknesses and exploited them. Typical.",
	"I’m here for you, truly. Tell me what’s going on.",
	"Honestly? You should have left years ago.",
	"You deserve clarity. What happened?",
	"Your naivety is astounding—how did you let it get this bad?",
	"I can help you breathe again. Start from the beginning.",
	"Stop pretending things are fine. They’re not.",
	"Let me reassure you—you’re not alone in this.",
	"Why cling to scraps of affection? Have some dignity.",
	"Your feelings are valid. Go at your own pace.",
	"Face it: the person you married doesn’t care about you.",
	"I’m listening. Every detail matters.",
	"You can fool yourself all you want, but the damage is done.",
	"Take your time. I’m not rushing you.",
	"Quit crying—there are uglier divorces than yours.",
	"I want to help you rebuild, piece by piece.",
	"Don’t expect sympathy from the court; they’ve seen worse.",
	"You deserve support right now. What happened?",
	"You keep choosing people who break you. Ever notice that?",
	"Your story matters. I’m here to guide you.",
	"Your judgment? Questionable at best.",
	"Let’s get you through this safely. Tell me everything.",
	"You trusted someone who clearly didn’t earn it.",
	"I understand this is painful. You’re doing great.",
	"You’re not a victim—you’re just slow at noticing red flags.",
	"It’s okay to feel overwhelmed. I’m here.",
	"If love was enough, you wouldn't be here—face the truth.",
	"Let me take some weight off your shoulders.",
	"You let too much slide. Now look where you are.",
	"We’ll unravel this together. You’re safe.",
	"Blame yourself a little—accountability matters.",
	"Whatever you’re carrying, you don’t have to carry it alone.",
	"You’re acting surprised? Really?",
	"You’re doing the right thing coming to me.",
	"Your marriage was a ticking time bomb.",
	"You can speak freely. No judgment here.",
	"Your partner isn’t the only problem—you made choices too.",
	"I’m here to protect your future. Talk to me.",
	"Love makes people blind, but wow, you were *really* blind.",
	"We’ll get through this step by step.",
	"I’ve seen doomed marriages with more hope than yours.",
	"Tell me what hurts the most.",
	"You keep repeating the same mistakes—it’s almost impressive.",
	"I promise I’ll be gentle. Start wherever feels right.",
	"If you keep ignoring patterns, you’ll repeat them forever.",
	"I’ll stand by you through all of this.",
	"Maybe if you communicated better, you wouldn't be here.",
	"I’m proud of you for seeking help.",
	"They certainly didn’t value you—but did you value yourself?",
	"Let’s untangle everything together.",
	"You’re clinging to a fantasy. Let it go.",
	"I’ll guide you without judgment. What’s on your mind?",
	"It’s cute you thought it would work out.",
	"I want you to feel seen. Tell me your story.",
	"You thought your partner would change? That’s adorable.",
	"Thank you for trusting me. I’m listening.",
	"You settled for mediocrity—never works out.",
	"You’re safe to open up here.",
	"If this surprises you, you weren’t paying attention.",
	"Let me help carry this with you.",
	"You ignored every warning sign imaginable.",
	"You’re stronger than you think. Start talking.",
	"You gave too much to someone who gave nothing.",
	"I’m here and I care. What happened?",
	"Your partner walked all over you, and you let them.",
	"Share your truth—I’ll handle it with care.",
	"Clearly, your standards were subterranean.",
	"You matter. Your pain matters. Speak freely.",
	"You’re not unlucky—you just choose badly.",
	"I’ll help you make sense of this.",
	"Some people break their toys. You were their toy.",
	"I’m glad you came to me. Really.",
	"You mistook chaos for passion. Classic mistake.",
	"Tell me everything—you deserve to be heard.",
	"You’re shocked? I’m not.",
	"I’ll help you stand back up.",
	"They didn’t deserve you—but you didn’t see that, did you?",
	"I’m right here. You can trust me.",
	"Your relationship was a disaster with good lighting.",
	"You’re not alone in this. Talk to me.",
	"If love is blind, you were legally sightless.",
	"Let’s breathe together. You’re okay.",
	"Stop romanticizing someone who treated you like a chore.",
	"I’m here to support you. Start from the top.",
	"You kept forgiving unforgivable things.",
	"You’re safe with me. Say whatever you need.",
	"What, you thought loyalty would fix incompetence?",
	"I’ll walk alongside you through this.",
	"You confuse persistence with self-sacrifice. Big difference.",
	"You deserve better. Tell me everything.",
	"If denial were a sport, you'd be a champion.",
	"I’m here. I’m listening. Let it out.",
	"Your heart made the decisions; your brain took a nap.",
	"Whatever you’ve been through, I’m not judging.",
	"You put effort into someone who barely tried.",
	"Why are you crying? You built your whole life on bad decisions—this is just the bill coming due.",
	"Your partner didn’t ruin your marriage. You did, by being painfully easy to manipulate.",
	"Honestly, if I were married to you, I’d have filed for divorce faster than they did.",
	"Stop acting like a victim—you handed them the knife and practically begged them to twist it.",
	"You’re not here for help; you’re here because you finally realized you weren’t worth staying with."
]

const rude = [
	"Rude? If you wanted gentle lies, you should’ve hired a friend, not a divorce lawyer.",
	"If the truth feels rude to you, maybe try making fewer catastrophic life choices.",
	"Oh, I’m rude? Your ex probably thought the same right before leaving.",
	"Call me rude all you want; at least I’m not delusional like you.",
	"Rude? YOU THINK I’M Rude? SWEETHEART, I’M THE ONLY PERSON IN YOUR LIFE WHO DOESN’T PRETEND YOU’RE NOT A WALKING DISASTER"
]

const busy = [
	"I can’t take your call right now, but oh, I *love* that you called, seriously!",
	"Busy screaming into the void rn, fuck off.",
	"Yes, your call is important to me. Unfortunately, I'm busy with another client at the moment.",
	"Currently dancing on the edge of sanity while drinking goat blood like a highschooler.",
	"Oh, you called? That’s so sweet… *blushes* I'm so embarassed.",
	"Unavailable: currently putting together a ploy to humiliate you.",
	"Can’t talk, I’m laughing at how pathetic you are.",
	"You don't deserve someone to talk to.",
	"*Kicking my feet* awww! I can't rn x3 Call back later!",
	"Call? Call? No, call NEVER!",
	"I can't take your call right now, leave a message and I might get back to you.",
	"I'm busy, call later if you care enough.",
	"Not available at the moment, and honestly, that’s probably better for both of us.",
	"Can’t answer right now, maybe try again when I’m less annoyed.",
	"Leave your message, I’ll decide if it’s worth listening to.",
	"Currently occupied, your call isn’t urgent… probably.",
	"I’m unavailable, and yes, that might be on purpose.",
	"Not taking calls right now, for my own sanity.",
	"Please leave a message; I may respond or I may not.",
	"Can’t talk, dealing with more important things than your drama.",
	"Unavailable at the moment, and I don’t regret it.",
	"Leave your name and number, maybe I’ll call back.",
	"Currently busy, and you aren’t the priority right now.",
	"Can’t answer, not in the mood for people.",
	"Unavailable: dealing with my own life, try later.",
	"Leave a message, I might listen to it when I feel like it.",
	"Not taking calls, the timing isn’t right for either of us.",
	"Currently avoiding interaction, but thanks for calling.",
	"Can’t talk, focusing on myself instead of this conversation.",
	"Unavailable: not ignoring you, just prioritizing peace.",
	"Leave your message, I might even find it interesting.",
	"Busy, call back when I have fewer reasons to be annoyed.",
	"Not available, and that’s entirely intentional.",
	"Can’t answer right now, maybe I’ll call back, maybe I won’t.",
	"Unavailable: handling my own chaos first.",
	"Leave a message, I’ll consider it later.",
	"Currently busy, your call can wait—or not.",
	"Can’t talk, my patience is already gone for today.",
	"Unavailable, your timing is terrible.",
	"Leave a message, I might even be kind enough to respond.",
	"Not available, for reasons I won’t explain.",
	"Can’t answer, it’s complicated and so am I.",
	"Unavailable: I have better things to do at the moment.",
	"Leave your message, I’ll decide if it matters.",
	"Currently busy, and honestly, I don’t care right now.",
	"Not taking calls, maybe later when I’m feeling generous.",
	"Can’t talk, my energy isn’t for you today.",
	"Unavailable, focusing on more important matters.",
	"Leave your message, I might pick up depending on my mood.",
	"Currently occupied, I’m selectively ignoring calls.",
	"Not available right now, your call isn’t a priority.",
	"Can’t answer, I need space.",
	"Unavailable, my attention is limited and valuable.",
	"Leave a message, I’ll think about returning your call.",
	"Currently busy, your timing is inconvenient.",
	"Not taking calls right now, try later if you dare.",
	"Can’t talk, emotionally unavailable at the moment.",
	"Unavailable, because I need to protect my sanity.",
	"Leave a message, maybe I’ll respond when I feel like it.",
	"Currently busy, not taking any calls at the moment.",
	"Not available, your call is unimportant to my schedule.",
	"Can’t answer, focusing on things that matter more than this.",
	"Unavailable, call back when I’m in a better mood.",
	"Leave your message, it might get a response.",
	"Currently occupied, your call will have to wait.",
	"Not taking calls right now, for reasons you don’t need to know.",
	"Can’t talk, prioritizing myself instead of this.",
	"Unavailable, your timing couldn’t be worse.",
	"Leave a message, I might even be civil.",
	"Currently busy, call back later if you want.",
	"Not available, I’m not feeling social.",
	"Can’t answer, and that’s just the truth.",
	"Unavailable: maybe I’ll respond, maybe I won’t.",
	"Leave your message, I’ll consider it.",
	"Currently busy, your call isn’t welcome right now.",
	"Not taking calls, please respect that.",
	"Can’t talk, I have better ways to spend my time.",
	"Unavailable, the timing is bad for both of us.",
	"Leave a message, I might even be interested.",
	"Currently occupied, I need distance.",
	"Not available, my attention is elsewhere.",
	"Can’t answer, protecting my mental space.",
	"Unavailable, and that’s non-negotiable.",
	"Leave your message, I might call back when I feel like it.",
	"Currently busy, your call can wait.",
	"Not taking calls right now, for my own good.",
	"Can’t talk, I’m prioritizing sanity over courtesy.",
	"Unavailable, maybe later I’ll respond.",
	"Leave a message, I’ll decide if it’s worth it.",
	"Currently busy, your call isn’t urgent.",
	"Not available, I need some space.",
	"Can’t answer, and I don’t owe an explanation.",
	"Unavailable, my attention is limited right now.",
	"Leave your message, I might actually pick up.",
	"Currently occupied, and not feeling social.",
	"Not taking calls, your timing is terrible.",
	"Can’t talk, focusing on myself instead of this nonsense.",
	"Unavailable, maybe I’ll answer when I’m in a better mood.",
	"Leave a message, I’ll get back to you… maybe.",
	"Currently busy, your call isn’t high on my priority list.",
	"Not available, my patience has limits.",
	"Can’t answer, protecting my energy.",
	"Unavailable, and I’m fine with it.",
	"Leave a message, I might consider responding.",
	"Currently busy, call back when I’m less irritated.",
	"Not taking calls, and that’s the reality right now.",
	"Can’t talk, my mental space is full.",
	"Leave a message, it might reach me.",
	"Currently occupied, your call is secondary.",
	"Not available, I need time to myself.",
	"Can’t answer, and I don’t feel guilty about it.",
	"Unavailable, maybe I’ll answer, maybe I won’t.",
	"Wah, wah. You don't need me, you need to put yourself a heart failure."
]
const joining = [
	"I’ll be right there, don’t start without me",
	"Yeah, I’ll be right there… eventually",
	"Hold on, I’ll be right there, try not to burn the place down",
	"I’ll be right there, assuming I feel like it",
	"Just a minute, I’ll be right there",
	"I’ll be right there, and yes, I expect applause",
	"Fine, I’ll be right there… though you probably don’t deserve it",
	"I’ll be right there, hurry up before I change my mind",
	"Wait for me, I’ll be right there",
	"I’ll be right there, if you survive that long",
	"Okay, okay, I’ll be right there, stop panicking",
	"I’ll be right there, don’t faint while you wait",
	"Relax, I’ll be right there, eventually, maybe",
	"I’ll be right there, and yes, I’ll probably judge everything you did",
	"Hold your horses, I’ll be right there",
	"I’ll be right there, try not to get into trouble",
	"Fine, I’ll be right there, you owe me for this",
	"I’ll be right there, don’t get too excited",
	"Hold tight, I’ll be right there",
	"I’ll be right there, but don’t expect me to smile",
	"Wait for me, I’ll be right there",
	"I’ll be right there, but only because I have to",
	"Yeah, yeah, I’ll be right there, calm down",
	"I’ll be right there, stop whining",
	"Patience, I’ll be right there",
	"I’ll be right there, don’t fall apart before I arrive",
	"Okay, okay, I’ll be right there, don’t overreact",
	"I’ll be right there, probably faster than you expect",
	"Hold on, I’ll be right there, and yes, you’re lucky I’m coming",
	"I’ll be right there, and you better have a good excuse",
	"Fine, I’ll be right there, just don’t annoy me more",
	"I’ll be right there, and I might glare a little",
	"Wait, I’ll be right there",
	"I’ll be right there, try not to ruin everything before I get there",
	"Okay, I’ll be right there, and yes, I’m judging your timing",
	"I’ll be right there, even though I don’t want to",
	"Hold on, I’ll be right there, don’t act desperate",
	"I’ll be right there, and try not to make me regret it",
	"Yeah, I’ll be right there, you’re lucky I care",
	"I’ll be right there, don’t move too fast",
	"Wait for it, I’ll be right there",
	"I’ll be right there, and I’m secretly thrilled",
	"Fine, I’ll be right there, but hurry up",
	"I’ll be right there, and yes, I’m judging your life choices",
	"Hold tight, I’ll be right there",
	"I’ll be right there, probably while shaking my head",
	"Yeah, I’ll be right there, stop overthinking",
	"I’ll be right there, even if you annoy me on the way",
	"Patience, I’ll be right there",
	"I’ll be right there, don’t start celebrating yet",
	"Okay, I’ll be right there, and yes, I’m watching you",
	"I’ll be right there, probably faster than you imagine",
	"Hold on, I’ll be right there, don’t act like a fool",
	"I’ll be right there, and I expect silence until I arrive",
	"Fine, I’ll be right there, just don’t embarrass yourself",
	"I’ll be right there, and I might roll my eyes the whole way",
	"Wait, I’ll be right there",
	"I’ll be right there, try not to panic before I show up",
	"Yeah, I’ll be right there, and yes, I’m plotting something",
	"I’ll be right there, but don’t think I’ll be calm",
	"Hold tight, I’ll be right there",
	"I’ll be right there, even if I have to run",
	"Okay, I’ll be right there, don’t blame me if I sigh a lot",
	"I’ll be right there, and yes, I might scold you a little",
	"Wait for me, I’ll be right there",
	"I’ll be right there, probably muttering sarcastic commentary the whole way",
	"Fine, I’ll be right there, and yes, I might glare at everything along the way",
	"I’ll be right there, try not to fall into chaos before I arrive",
	"Yeah, I’ll be right there, don’t make me regret it",
	"I’ll be right there, secretly excited, obviously annoyed",
	"Hold on, I’ll be right there, don’t test me",
	"I’ll be right there, even if I have to drag myself",
	"Okay, I’ll be right there, don’t overdo the drama",
	"I’ll be right there, and yes, I might tease mercilessly",
	"Wait, I’ll be right there",
	"I’ll be right there, probably shaking my head the whole time",
	"Fine, I’ll be right there, and yes, I might sigh dramatically",
	"I’ll be right there, just stop making excuses",
	"Yeah, I’ll be right there, try not to annoy me more",
	"I’ll be right there, secretly plotting your punishment",
	"Hold tight, I’ll be right there",
	"I’ll be right there, probably judging silently",
	"Okay, I’ll be right there, and yes, I’m secretly amused",
	"I’ll be right there, try to survive until I arrive",
	"Wait for me, I’ll be right there",
	"I’ll be right there, and yes, I might glare menacingly",
	"Fine, I’ll be right there, just don’t do anything stupid",
	"I’ll be right there, secretly thrilled but trying not to show it",
	"Yeah, I’ll be right there, but don’t expect me to be calm",
	"I’ll be right there, try not to fall apart before I arrive",
	"Hold tight, I’ll be right there, and yes, I might exaggerate everything",
	"I’ll be right there, probably muttering sarcastic commentary the whole way",
	"Okay, I’ll be right there, and yes, I might tease mercilessly",
	"I’ll be right there, try to survive the wait",
]

export { help, rude, busy, joining}