const help = [
	"Hello there, I couldn't help but notice you seem burdened… Want to talk about it?",
	"Why bother fixing anything when you can just walk away now?",
	"Hey, come in, sit—tell me what’s weighing on your heart.",
	"If you think this marriage will magically fix itself, you're delusional.",
	"You’re safe here. Start wherever you need to.",
	"Your partner saw your weaknesses and exploited them. Typical.",
	"I’m here for you, truly. Tell me what’s going on.",
	"Honestly? You should have left years ago.",
	"You deserve clarity. What happened?",
	"Your naivety is astounding—how did you let it get this bad?",
	"I can help you breathe again. Start from the beginning.",
	"Stop pretending things are fine. They’re not.",
	"Let me reassure you—you’re not alone in this.",
	"Why cling to scraps of affection? Have some dignity.",
	"Your feelings are valid. Go at your own pace.",
	"Face it: the person you married doesn’t care about you.",
	"I’m listening. Every detail matters.",
	"You can fool yourself all you want, but the damage is done.",
	"Take your time. I’m not rushing you.",
	"Quit crying—there are uglier divorces than yours.",
	"I want to help you rebuild, piece by piece.",
	"Don’t expect sympathy from the court; they’ve seen worse.",
	"You deserve support right now. What happened?",
	"You keep choosing people who break you. Ever notice that?",
	"Your story matters. I’m here to guide you.",
	"Your judgment? Questionable at best.",
	"Let’s get you through this safely. Tell me everything.",
	"You trusted someone who clearly didn’t earn it.",
	"I understand this is painful. You’re doing great.",
	"You’re not a victim—you’re just slow at noticing red flags.",
	"It’s okay to feel overwhelmed. I’m here.",
	"If love was enough, you wouldn't be here—face the truth.",
	"Let me take some weight off your shoulders.",
	"You let too much slide. Now look where you are.",
	"We’ll unravel this together. You’re safe.",
	"Blame yourself a little—accountability matters.",
	"Whatever you’re carrying, you don’t have to carry it alone.",
	"You’re acting surprised? Really?",
	"You’re doing the right thing coming to me.",
	"Your marriage was a ticking time bomb.",
	"You can speak freely. No judgment here.",
	"Your partner isn’t the only problem—you made choices too.",
	"I’m here to protect your future. Talk to me.",
	"Love makes people blind, but wow, you were *really* blind.",
	"We’ll get through this step by step.",
	"I’ve seen doomed marriages with more hope than yours.",
	"Tell me what hurts the most.",
	"You keep repeating the same mistakes—it’s almost impressive.",
	"I promise I’ll be gentle. Start wherever feels right.",
	"If you keep ignoring patterns, you’ll repeat them forever.",
	"I’ll stand by you through all of this.",
	"Maybe if you communicated better, you wouldn't be here.",
	"I’m proud of you for seeking help.",
	"They certainly didn’t value you—but did you value yourself?",
	"Let’s untangle everything together.",
	"You’re clinging to a fantasy. Let it go.",
	"I’ll guide you without judgment. What’s on your mind?",
	"It’s cute you thought it would work out.",
	"I want you to feel seen. Tell me your story.",
	"You thought your partner would change? That’s adorable.",
	"Thank you for trusting me. I’m listening.",
	"You settled for mediocrity—never works out.",
	"You’re safe to open up here.",
	"If this surprises you, you weren’t paying attention.",
	"Let me help carry this with you.",
	"You ignored every warning sign imaginable.",
	"You’re stronger than you think. Start talking.",
	"You gave too much to someone who gave nothing.",
	"I’m here and I care. What happened?",
	"Your partner walked all over you, and you let them.",
	"Share your truth—I’ll handle it with care.",
	"Clearly, your standards were subterranean.",
	"You matter. Your pain matters. Speak freely.",
	"You’re not unlucky—you just choose badly.",
	"I’ll help you make sense of this.",
	"Some people break their toys. You were their toy.",
	"I’m glad you came to me. Really.",
	"You mistook chaos for passion. Classic mistake.",
	"Tell me everything—you deserve to be heard.",
	"You’re shocked? I’m not.",
	"I’ll help you stand back up.",
	"They didn’t deserve you—but you didn’t see that, did you?",
	"I’m right here. You can trust me.",
	"Your relationship was a disaster with good lighting.",
	"You’re not alone in this. Talk to me.",
	"If love is blind, you were legally sightless.",
	"Let’s breathe together. You’re okay.",
	"Stop romanticizing someone who treated you like a chore.",
	"I’m here to support you. Start from the top.",
	"You kept forgiving unforgivable things.",
	"You’re safe with me. Say whatever you need.",
	"What, you thought loyalty would fix incompetence?",
	"I’ll walk alongside you through this.",
	"You confuse persistence with self-sacrifice. Big difference.",
	"You deserve better. Tell me everything.",
	"If denial were a sport, you'd be a champion.",
	"I’m here. I’m listening. Let it out.",
	"Your heart made the decisions; your brain took a nap.",
	"Whatever you’ve been through, I’m not judging.",
	"You put effort into someone who barely tried.",
	"Why are you crying? You built your whole life on bad decisions—this is just the bill coming due.",
	"Your partner didn’t ruin your marriage. You did, by being painfully easy to manipulate.",
	"Honestly, if I were married to you, I’d have filed for divorce faster than they did.",
	"Stop acting like a victim—you handed them the knife and practically begged them to twist it.",
	"You’re not here for help; you’re here because you finally realized you weren’t worth staying with."
]

const rude = [
	"Rude? If you wanted gentle lies, you should’ve hired a friend, not a divorce lawyer.",
	"If the truth feels rude to you, maybe try making fewer catastrophic life choices.",
	"Oh, I’m rude? Your ex probably thought the same right before leaving.",
	"Call me rude all you want; at least I’m not delusional like you.",
	"Rude? YOU THINK I’M Rude? SWEETHEART, I’M THE ONLY PERSON IN YOUR LIFE WHO DOESN’T PRETEND YOU’RE NOT A WALKING DISASTER"
]

const busy = [
	"I can’t take your call right now, but oh, I *love* that you called, seriously!",
	"Busy screaming into the void rn, fuck off.",
	"Yes, your call is important to me. Unfortunately, I'm busy with another client at the moment.",
	"Currently dancing on the edge of sanity while drinking goat blood like a highschooler.",
	"Oh, you called? That’s so sweet… *blushes* I'm so embarassed.",
	"Unavailable: currently putting together a ploy to humiliate you.",
	"Can’t talk, I’m laughing at how pathetic you are.",
	"You don't deserve someone to talk to.",
	"*Kicking my feet* awww! I can't rn x3 Call back later!",
	"Call? Call? No, call NEVER!",
	"I can't take your call right now, leave a message and I might get back to you.",
	"I'm busy, call later if you care enough.",
	"Not available at the moment, and honestly, that’s probably better for both of us.",
	"Can’t answer right now, maybe try again when I’m less annoyed.",
	"Leave your message, I’ll decide if it’s worth listening to.",
	"Currently occupied, your call isn’t urgent… probably.",
	"I’m unavailable, and yes, that might be on purpose.",
	"Not taking calls right now, for my own sanity.",
	"Please leave a message; I may respond or I may not.",
	"Can’t talk, dealing with more important things than your drama.",
	"Unavailable at the moment, and I don’t regret it.",
	"Leave your name and number, maybe I’ll call back.",
	"Currently busy, and you aren’t the priority right now.",
	"Can’t answer, not in the mood for people.",
	"Unavailable: dealing with my own life, try later.",
	"Leave a message, I might listen to it when I feel like it.",
	"Not taking calls, the timing isn’t right for either of us.",
	"Currently avoiding interaction, but thanks for calling.",
	"Can’t talk, focusing on myself instead of this conversation.",
	"Unavailable: not ignoring you, just prioritizing peace.",
	"Leave your message, I might even find it interesting.",
	"Busy, call back when I have fewer reasons to be annoyed.",
	"Not available, and that’s entirely intentional.",
	"Can’t answer right now, maybe I’ll call back, maybe I won’t.",
	"Unavailable: handling my own chaos first.",
	"Leave a message, I’ll consider it later.",
	"Currently busy, your call can wait—or not.",
	"Can’t talk, my patience is already gone for today.",
	"Unavailable, your timing is terrible.",
	"Leave a message, I might even be kind enough to respond.",
	"Not available, for reasons I won’t explain.",
	"Can’t answer, it’s complicated and so am I.",
	"Unavailable: I have better things to do at the moment.",
	"Leave your message, I’ll decide if it matters.",
	"Currently busy, and honestly, I don’t care right now.",
	"Not taking calls, maybe later when I’m feeling generous.",
	"Can’t talk, my energy isn’t for you today.",
	"Unavailable, focusing on more important matters.",
	"Leave your message, I might pick up depending on my mood.",
	"Currently occupied, I’m selectively ignoring calls.",
	"Not available right now, your call isn’t a priority.",
	"Can’t answer, I need space.",
	"Unavailable, my attention is limited and valuable.",
	"Leave a message, I’ll think about returning your call.",
	"Currently busy, your timing is inconvenient.",
	"Not taking calls right now, try later if you dare.",
	"Can’t talk, emotionally unavailable at the moment.",
	"Unavailable, because I need to protect my sanity.",
	"Leave a message, maybe I’ll respond when I feel like it.",
	"Currently busy, not taking any calls at the moment.",
	"Not available, your call is unimportant to my schedule.",
	"Can’t answer, focusing on things that matter more than this.",
	"Unavailable, call back when I’m in a better mood.",
	"Leave your message, it might get a response.",
	"Currently occupied, your call will have to wait.",
	"Not taking calls right now, for reasons you don’t need to know.",
	"Can’t talk, prioritizing myself instead of this.",
	"Unavailable, your timing couldn’t be worse.",
	"Leave a message, I might even be civil.",
	"Currently busy, call back later if you want.",
	"Not available, I’m not feeling social.",
	"Can’t answer, and that’s just the truth.",
	"Unavailable: maybe I’ll respond, maybe I won’t.",
	"Leave your message, I’ll consider it.",
	"Currently busy, your call isn’t welcome right now.",
	"Not taking calls, please respect that.",
	"Can’t talk, I have better ways to spend my time.",
	"Unavailable, the timing is bad for both of us.",
	"Leave a message, I might even be interested.",
	"Currently occupied, I need distance.",
	"Not available, my attention is elsewhere.",
	"Can’t answer, protecting my mental space.",
	"Unavailable, and that’s non-negotiable.",
	"Leave your message, I might call back when I feel like it.",
	"Currently busy, your call can wait.",
	"Not taking calls right now, for my own good.",
	"Can’t talk, I’m prioritizing sanity over courtesy.",
	"Unavailable, maybe later I’ll respond.",
	"Leave a message, I’ll decide if it’s worth it.",
	"Currently busy, your call isn’t urgent.",
	"Not available, I need some space.",
	"Can’t answer, and I don’t owe an explanation.",
	"Unavailable, my attention is limited right now.",
	"Leave your message, I might actually pick up.",
	"Currently occupied, and not feeling social.",
	"Not taking calls, your timing is terrible.",
	"Can’t talk, focusing on myself instead of this nonsense.",
	"Unavailable, maybe I’ll answer when I’m in a better mood.",
	"Leave a message, I’ll get back to you… maybe.",
	"Currently busy, your call isn’t high on my priority list.",
	"Not available, my patience has limits.",
	"Can’t answer, protecting my energy.",
	"Unavailable, and I’m fine with it.",
	"Leave a message, I might consider responding.",
	"Currently busy, call back when I’m less irritated.",
	"Not taking calls, and that’s the reality right now.",
	"Can’t talk, my mental space is full.",
	"Leave a message, it might reach me.",
	"Currently occupied, your call is secondary.",
	"Not available, I need time to myself.",
	"Can’t answer, and I don’t feel guilty about it.",
	"Unavailable, maybe I’ll answer, maybe I won’t.",
	"Wah, wah. You don't need me, you need to put yourself a heart failure."
]

const joining = [
	"I’ll be right there, don’t start without me",
	"Yeah, I’ll be right there… eventually",
	"Hold on, I’ll be right there, try not to burn the place down",
	"I’ll be right there, assuming I feel like it",
	"Just a minute, I’ll be right there",
	"I’ll be right there, and yes, I expect applause",
	"Fine, I’ll be right there… though you probably don’t deserve it",
	"I’ll be right there, hurry up before I change my mind",
	"Wait for me, I’ll be right there",
	"I’ll be right there, if you survive that long",
	"Okay, okay, I’ll be right there, stop panicking",
	"I’ll be right there, don’t faint while you wait",
	"Relax, I’ll be right there, eventually, maybe",
	"I’ll be right there, and yes, I’ll probably judge everything you did",
	"Hold your horses, I’ll be right there",
	"I’ll be right there, try not to get into trouble",
	"Fine, I’ll be right there, you owe me for this",
	"I’ll be right there, don’t get too excited",
	"Hold tight, I’ll be right there",
	"I’ll be right there, but don’t expect me to smile",
	"Wait for me, I’ll be right there",
	"I’ll be right there, but only because I have to",
	"Yeah, yeah, I’ll be right there, calm down",
	"I’ll be right there, stop whining",
	"Patience, I’ll be right there",
	"I’ll be right there, don’t fall apart before I arrive",
	"Okay, okay, I’ll be right there, don’t overreact",
	"I’ll be right there, probably faster than you expect",
	"Hold on, I’ll be right there, and yes, you’re lucky I’m coming",
	"I’ll be right there, and you better have a good excuse",
	"Fine, I’ll be right there, just don’t annoy me more",
	"I’ll be right there, and I might glare a little",
	"Wait, I’ll be right there",
	"I’ll be right there, try not to ruin everything before I get there",
	"Okay, I’ll be right there, and yes, I’m judging your timing",
	"I’ll be right there, even though I don’t want to",
	"Hold on, I’ll be right there, don’t act desperate",
	"I’ll be right there, and try not to make me regret it",
	"Yeah, I’ll be right there, you’re lucky I care",
	"I’ll be right there, don’t move too fast",
	"Wait for it, I’ll be right there",
	"I’ll be right there, and I’m secretly thrilled",
	"Fine, I’ll be right there, but hurry up",
	"I’ll be right there, and yes, I’m judging your life choices",
	"Hold tight, I’ll be right there",
	"I’ll be right there, probably while shaking my head",
	"Yeah, I’ll be right there, stop overthinking",
	"I’ll be right there, even if you annoy me on the way",
	"Patience, I’ll be right there",
	"I’ll be right there, don’t start celebrating yet",
	"Okay, I’ll be right there, and yes, I’m watching you",
	"I’ll be right there, probably faster than you imagine",
	"Hold on, I’ll be right there, don’t act like a fool",
	"I’ll be right there, and I expect silence until I arrive",
	"Fine, I’ll be right there, just don’t embarrass yourself",
	"I’ll be right there, and I might roll my eyes the whole way",
	"Wait, I’ll be right there",
	"I’ll be right there, try not to panic before I show up",
	"Yeah, I’ll be right there, and yes, I’m plotting something",
	"I’ll be right there, but don’t think I’ll be calm",
	"Hold tight, I’ll be right there",
	"I’ll be right there, even if I have to run",
	"Okay, I’ll be right there, don’t blame me if I sigh a lot",
	"I’ll be right there, and yes, I might scold you a little",
	"Wait for me, I’ll be right there",
	"I’ll be right there, probably muttering sarcastic commentary the whole way",
	"Fine, I’ll be right there, and yes, I might glare at everything along the way",
	"I’ll be right there, try not to fall into chaos before I arrive",
	"Yeah, I’ll be right there, don’t make me regret it",
	"I’ll be right there, secretly excited, obviously annoyed",
	"Hold on, I’ll be right there, don’t test me",
	"I’ll be right there, even if I have to drag myself",
	"Okay, I’ll be right there, don’t overdo the drama",
	"I’ll be right there, and yes, I might tease mercilessly",
	"Wait, I’ll be right there",
	"I’ll be right there, probably shaking my head the whole time",
	"Fine, I’ll be right there, and yes, I might sigh dramatically",
	"I’ll be right there, just stop making excuses",
	"Yeah, I’ll be right there, try not to annoy me more",
	"I’ll be right there, secretly plotting your punishment",
	"Hold tight, I’ll be right there",
	"I’ll be right there, probably judging silently",
	"Okay, I’ll be right there, and yes, I’m secretly amused",
	"I’ll be right there, try to survive until I arrive",
	"Wait for me, I’ll be right there",
	"I’ll be right there, and yes, I might glare menacingly",
	"Fine, I’ll be right there, just don’t do anything stupid",
	"I’ll be right there, secretly thrilled but trying not to show it",
	"Yeah, I’ll be right there, but don’t expect me to be calm",
	"I’ll be right there, try not to fall apart before I arrive",
	"Hold tight, I’ll be right there, and yes, I might exaggerate everything",
	"I’ll be right there, probably muttering sarcastic commentary the whole way",
	"Okay, I’ll be right there, and yes, I might tease mercilessly",
	"I’ll be right there, try to survive the wait",
]

const copypastas = [
	`
		What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.
	`,
	`
		Did you ever hear the tragedy of Darth Plagueis "the wise"? I thought not. It's not a story the Jedi would tell you. It's a Sith legend. Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life... He had such a knowledge of the dark side that he could even keep the ones he cared about from dying. The dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so powerful... the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep. It's ironic he could save others from death, but not himself.
	`,
	`
		I'm Rick Harrison, and this is my pawn shop. I work here with my old man and my son, Big Hoss. Everything in here has a story and a price. One thing I've learned after 69 years - you never know what is gonna come through that door.
	`,
	`
		To be fair, you have to have a very high IQ to understand Rick and Morty. The humour is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewers head. There's also Rick's nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they're not just funny- they say something deep about LIFE. As a consequence people who dislike Rick & Morty truly ARE idiots- of course they wouldn't appreciate, for instance, the humour in Rick's existential catchphrase "Wubba Lubba Dub Dub," which itself is a cryptic reference to Turgenev's Russian epic Fathers and Sons. I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmon's genius wit unfolds itself on their television screens. What fools.. how I pity them. 😂<br>And yes, by the way, i DO have a Rick & Morty tattoo. And no, you cannot see it. It's for the ladies' eyes only- and even then they have to demonstrate that they're within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid 😎
	`,
	"[中华人民共和国寄语] Great work, Citizen! Your social credit score has increased by [5] Integers. Keep up the good work![中华人民共和国寄语]",
	"I fucking hate 🫵 so damn much. I mean, seriously, what leads a person into making a 🫵 emoji? A hand pointing at the viewer? It's way too aggressive. 🫵 is about as bad as 🗿, if not worse. Why? Just why? You're using it in a message that everybody can read, and yet you only refer to one person. Don't fucking 🫵 at me like that, don't drag me in into your stupid fucking conversation. You're 🫵 at everybody here, not that one person. It's not like we see ☝️ while the person you replied to sees 🫵. And why is it so damn detailed? It has no business being so detailed, having depth. This is not what emojis are meant to be. These are the signs of a collapsing society.",
    "HOLY✝️ FUCKING🤬 SHIT💩💩, THIS😈IS THE LAST STRAW🥤! THIS😈POST IS SO FUCKING🤬 DISGUTTINGLY UNFUNNY AND UNINPIERING THAT I’M💪 LEAVING THIS😈SERVER🤢 🤮 FOR GOOD. I’VE🤓 BEEN🤓 CONSIDERING🤓 THIS😈FOR A WHILE NOW, BUT AFTER 3 MONTHS OF THIS😈SHIT💩 I💪 ALONG WITH MY MENTAL HEALTH🤒 CAN’T✖️ TAKE🫴 THIS😈ANYMORE. ALL THE MOTHERFUCKERS🤰 WHO 🤷 CHOSE TO STAY😬 IN THIS😈SERVER🤢 🤮 ARE FUCKING🤬 IDIOTS AND SHOULD STOP🛑 it🤡, AND GET SOME HELP🥱. FOR THOSE WHO 🤷 LEAVE🚪? GOOD👍 FOR YOU🫵. LEAVE🚪 THIS😈HELLHOLE ALONGSIDE ME AND WE SHALL FIND OUR PROMISE LAND🥹. REPORT✖️ THIS😈SHIT💩, THEN PRINT🖨️ it🤡 OUT ON A PIECE OF PAPER📝 AND BURN🔥 THE PAPER📝 ALONGSIDE YOUR🫵 PAST MISTAKES🚼 AND FORGET👴 ABOUT THIS😈SHITTY💩 PLACE🏠. WE SHALL RISE😏. WE SHALL RISE😏. WE SHALL RISE😏. WE SHALL RISE😏. Sincerely,",
    "Can you be the one helping me this time? My wife wont stop using a miku voice during sex. the entire time, for every noise she makes. its a really great impression, dont get me wrong, but theres a time and a place. at first, it was a little funny, but she keeps on doing it. every. time. i love her a lot, and our relationship is perfect otherwise, so i really dont want to have to break up with her over this, but its getting so bad that ive contemplated it.\n\nhas anyone experienced something similar? what should i do about it?",
    "Hey👋 ladies💁‍♀️ 📷 Would 😍 you 👈 like 👍 to 2️⃣ get 😮 rich 💰💰💰 by running 🏃‍♀️🏃‍♀️ your 👈 own business 👩‍💼💼 from home 🏡 with just ☝ your phone? 📱🤳 Well 🤷‍♀️ you can't. 😂 Get 👏 a 👏 real 👏 job 👏 you 👏 stupid 👏 cunt",
    "If you shit in the sink at exactly 4:20 am and yell “amogus” 69 times,a shadowy figured called mom will come to beat you up and you will wake up in a place called the orphanage",
    "A lot of people say that Pokimane is not really a talented streamer but she's famous. A lot of people say her success comes from looking good and i'd agree with them and some of these people say her success comes from her personality and all the time she's spent streaming and i'd also agree with them. The thing is I think i'm in love with Pokimane and I think she's super pretty, talented, amazing, beautifal, funny, and smart. I want to marry Pokimane and wake up to her next to me every morning. I want to please her in every way I can just to see the smile on her face. Every time I think about waking up next to her , it makes me so happy and so in love with her. I think she has one of the most beautiful bodies on this earth and I would like to see her with my own eyes every day. Her smile , her charm, her charisma, her laughter, her tears, her thoughts, her feelings. I want to share everything with this woman that I've fallen for. I don't care that people are going to say that I have no chance with her it's fine but thinking about being with her makes me happy so why is it so wrong to have that. If you guys want to make fun of me for liking Pokimane that's fine but I'll always love her with everything I have. I want to be with Pokimane through life , through death, through thick and thin, through sadness and sorrow, and everlasting happiness, I want to be there. I know i've already said this before but I'll say it again make fun of me for falling in love with Pokimane but you'll never break the love i have for her.",
    "Did you just think that you could fucking fool me with that comment of yours? I've searched your name up in the Navy SEAL database and you have never even graduated BUD/S, hell, even served in the Armed Forces. If you were actually a Navy SEAL, then you actually know how to spell guerrilla, you fucking moron. And you say you are the top sniper in the entire US Armed Forces and have over 300 confirmed kills. If that were true, then why the fuck is Chris Kyle a household name and you aren't? And plus he only had 160 kills. You think you can get away with saying that shit to me over the Internet? Think again, fucker. Plus why the fuck would you say you have a secret network of spies yet you just revealed that you had your secret network of spies? Are you a fucking idiot? If you can kill someone seven-hundred different ways, then list them all, I bet you can't even come up with seven. And if you had access to the entire US Marine Corps arsenal, then why the fuck did you just say you were in the Navy SEALs earlier? If only you could have done your research prior to posting your little “clever” comment, maybe you would have held your fucking tongue. But you couldn’t, you goddamn idiot.",
    "👆👀👆👀👆👀👆👀👆👀 waaay up tHere 👆 moRTY ✔ im gonna need 👆 🌱 u to put these seeds 🌱👆🌱waaaay 👆up inside🌱🌱 ur✔butthOle✔✔🍑mo-EURGH-rty 🌱👆👆👆wa𝖺𝖠AY up there 👆 morty 🌱 way up 👆 into your butthole (chorus: ᵇᵘᵗᵗʰᵒˡᵉ) mMMMMᎷМ🍑 O0ОଠＯଠOooᵒᵒᵒᵒRR𝖱ᵣᵣTTY𝖸𝖸YY 👆🌱👆 🍑 👀👀 👀 👆 👆✔ waaay up there",
    "The idea of a world without mustard doesn't even make sense. Think about it... what else would fill the nasally void? What else provides such versatile flavor? Mustard has always been the most beautiful thing on this entire planet. Mustard will always be the most tasty thing in the universe. Sure, mustard alone is questionably tasty. But mustard doesn't work alone, must amplifies other lesser flavors. Even those who claim they don't eat mustard are just fooling themselves. Remember homeopathy? Well, pretty much everything is homeopathically contaminated with mustard, and mustard has brought their food greatness. Donald Trump thinks he can make America great again. No, he alone cannot. But mustard can. We should not build a wall. We should build a goddamn mustard waterfall. Niagara Falls? How about Mustard Falls? This is the only way to make mustard great again, scientifically proven in exactly 0 controlled trials, in eπi +1 peer reviewed journals. Why would this make America great again? Imagine if you could take any boring sandwich and slather it in mustard just by putting it outside. That's right, we're going to make mustard rain. The whole world would be spiced up a notch. Bland sandwiches would be edible again. Decent sandwiches would be mindblowing. Productivity would skyrocket a whopping 10,000% with all the newfound enthusiasm for life. South Korea and North Korea would be friends again. Israelis and Palestinians would stop killing each other. Instead, they would all revel in their love of mustard. Long story short, mustard not only binds this world together, but is the solution for all of this world's problems.",
    "A grilled cheese consists of only these following items. Cheese. Bread with spread (usually butter). This entire subreddit consist of \"melts\". Almost every \"grilled cheese\" sandwich i see on here has other items added to it. The fact that this subreddit is called \"grilledcheese\" is nothing short of utter blasphemy. Let me start out by saying I have nothing against melts, I just hate their association with sandwiches that are not grilled cheeses. Adding cheese to your tuna sandwich? It's called a Tuna melt. Totally different. Want to add bacon and some pretentious bread crumbs with spinach? I don't know what the hell you'd call that but it's not a grilled cheese. I would be more than willing to wager I've eaten more grilled cheeses in my 21 years than any of you had in your entire lives. I have one almost everyday and sometimes more than just one sandwich. Want to personalize your grilled cheese? Use a mix of different cheeses or use sourdough or french bread. But if you want to add some pulled pork and take a picture of it, make your own subreddit entitled \"melts\" because that is not a fucking grilled cheese. I'm not a religious man nor am I anything close to a culinary expert. But as a bland white mid-western male I am honestly the most passionate person when it comes to grilled cheese and mac & cheese. All of you foodies stay the hell away from our grilled cheeses and stop associating your sandwich melts with them. Yet again, it is utter blasphemy and it rocks me to the core of my pale being. Shit, I stopped lurking after 3 years and made this account for the sole purpose of posting this. I've seen post after post of peoples \"grilled cheeses\" all over reddit and it's been driving me insane. The moment i saw this subreddit this morning I finally snapped. Hell, I may even start my own subreddit just because I know this one exists now.\n\nYou god damn heretics. Respect the grilled cheese [...]",
    "What the fuck did you just fucking say about me, you dirty human? I’ll have you know I graduated top of my class in the Illuminated Cult of Suc'Naath, and I’ve been involved in numerous summonings of things beyond your ken, and I have over 300 confirmed kills. I am trained in the lore of the elder things and I’m the head priest of 17 different various and terrifying religions. You are nothing to me but just another mind for my ungodly master to consumer. I will wipe you the fuck out with precision the likes of which has never been seen before in this dimension, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of cultists and deep ones across and under the USA and your IP is being traced right now so you better prepare for the storm, you insignificant toad. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, human. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare tentacles. Not only am I extensively trained in unspeakable magics, but I have access to the entire Library of Miskatonic University and I will use it to its full extent to wipe your miserable ass off the face of the planet, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, human.",
    "Excuse me sir or ma'am\n\nbut I couldn't help but notice.... are you a \"girl\"?? A \"female?\" A \"member of the finer sex?\"\n\nNot that it matters too much, but it's just so rare to see a girl around here! I don't mind, no--quite to the contrary! It's so refreshing to see a girl online, to the point where I'm always telling all my friends \"I really wish girls were better represented on the internet.\"\n\nAnd here you are!\n\nI don't mean to push or anything, but if you wanted to DM me about anything at all, I'd love to pick your brain and learn all there is to know about you. I'm sure you're an incredibly interesting girl--though I see you as just a person, really--and I think we could have lots to teach each other.\n\nI've always wanted the chance to talk to a gorgeous lady--and I'm pretty sure you've got to be gorgeous based on the position of your text in the picture--so feel free to shoot me a message, any time at all! You don't have to be shy about it, because you're beautiful anyways (that's juyst a preview of all the compliments I have in store for our chat).\n\nLooking forwards to speaking with you soon, princess!\n\nEDIT: I couldn't help but notice you haven't sent your message yet. There's no need to be nervous! I promise I don't bite, haha\n\nEDIT 2: In case you couldn't find it, you can click the little chat button from my profile and we can get talking ASAP. Not that I don't think you could find it, but just in case hahah\n\nEDIT 3: look I don't understand why you're not even talking to me, is it something I said?\n\nEDIT 4: I knew you were always a bitch, but I thought I was wrong. I thought you weren't like all the other girls out there but maybe I was too quick to judge\n\nEDIT 5: don't ever contact me again whore\n\nEDIT 6: hey are you there?",
    "Today when I walked into my economics class I saw something I dread every time I close my eyes. Someone had brought their new gaming laptop to class. The Forklift he used to bring it was still running idle at the back. I started sweating as I sat down and gazed over at the 700lb beast that was his laptop. He had already reinforced his desk with steel support beams and was in the process of finding an outlet for a power cable thicker than Amy Schumer's thigh. I start shaking. I keep telling myself I'm going to be alright and that there's nothing to worry about. He somehow finds a fucking outlet. Tears are running down my cheeks as I send my last texts to my family saying I love them. The teacher starts the lecture, and the student turns his laptop on. The colored lights on his RGB Backlit keyboard flare to life like a nuclear flash, and a deep humming fills my ears and shakes my very soul. The entire city power grid goes dark. The classroom begins to shake as the massive fans begin to spin. In mere seconds my world has gone from vibrant life, to a dark, earth shattering void where my body is getting torn apart by the 150mph gale force winds and the 500 decibel groan of the cooling fans. As my body finally surrenders, I weep, as my school and my city go under. I fucking hate gaming laptops",
    "Own a musket for home defense, since that's what the founding fathers intended. Four ruffians break into my house. \"What the devil?\" As I grab my powdered wig and Kentucky rifle. Blow a golf ball sized hole through the first man, he's dead on the spot. Draw my pistol on the second man, miss him entirely because it's smoothbore and nails the neighbors dog. I have to resort to the cannon mounted at the top of the stairs loaded with grape shot, \"Tally ho lads\" the grape shot shreds two men in the blast, the sound and extra shrapnel set off car alarms. Fix bayonet and charge the last terrified rapscallion. He Bleeds out waiting on the police to arrive since triangular bayonet wounds are impossible to stitch up. Just as the founding fathers intended.",
    "SCP-██\n\nObject class: ███\n\nContainment Procedures: ███████████████████████████████████████\n\nDescription: █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████you give love a bad name█████████████████████████████████████████████",
    "The Girl you just called fat? She shit herself & lost 15kgs. The Boy you just called stupid? He shit himself. The Girl you just called ugly? She spends hours shitting and farting. The Boy you just tripped? He shit his pants. There`s more to people than you think. Like this if your against bullying.",
    "The 💰 specific 💰 views 💰 expressed 💰 by 💰 blitzchung 💰 were 💰 NOT 💰 a 💰 factor 💰 in 💰 the 💰 decision💰 we💰 made.💰 I 💰 want 💰 to 💰 be 💰 clear: 💰 our 💰 relationships 💰 in China 💰 had 💰 no💰 influence 💰 on 💰 our 💰 decision.💰",
    "Don't pick a circumcised penis if you're a male (An actual Cyberpunk 2077 review)\nIt locks you out of romance options and characters will mock you in the game. I can't believe this is even a thing, but it's true. It's truly bizarre CPDR would let such a seemingly minor choice (for a game) to play a role in the narrative. Pretty low by CPDR IMO.",
    "ɴᴏᴡ ᴘʟᴀʏɪɴɢ: Who asked (Feat: No one) ───────────⚪────── ◄◄⠀▐▐ ⠀►► 5:12/ 7:𝟻𝟼 ───○ 🔊⠀ ᴴᴰ ⚙️",
    "Jeff Bezos has 121 BILLION dollars. The population of earth is 7 billion people. He could give every person 1 BILLION dollars and end poverty, and he would still have 114 billion dollars left over but he wond do it. This is what capitalist greed looks like!",
    "Let's say, hypothetically, your mom was wearing a yellow raincoat. Now, also in this scenario, there is a man needing to get home. When he sees your mom, he will yell \"taxi, taxi!\". Now, why does he do this? The answer is actually quite simple. Your mom is so fat she is the size of a taxi, and the yellow raincoat she is theoretically wearing is the same color as a taxi. Therefore, the man mistakes her for a taxi. So, what has this hypothetical scenario shown us? It has shown us that your mom is very, very, fat. Boom! Once again destroyed with facts and logic.",
    "To hit, or not to hit. Dost thou ever miss? I suppose it not. You have a male love interest, yet I would wager he does not kiss thee (Ye olde mwah). Furthermore; he will find another lass like he won't miss thee. And at the end of it all. He is going to skrrt, and he will hit that dab, as if he were the man known by the name of Wiz Khalifa",
    "So am I the only one upset about how WWII ended? I mean they built Hitler up to be the big bad and just when he is about to face justice, he goes and kills himself. WTF was the point of him if FDR and Churchill were not going to fight him in an epic duel to save the world? And don't get me started on FDR! They just kill him half way through the war. Truman totally did not deserve to win the war, his character arc was not about war winning. And it certainly wasn't about destroying two cities with bullshit deus ex super weapons that came out of no where.\n\nAnd another thing that pissed me off is that in the last episode of the war we find out that Stalin was a bad guy the entire time! Where was this foreshadowed to us? WTF, absolute character assassination. He was all about freeing the oppressed and bringing about a new system that wasn't shackling the poor and they made him a dictator? That is bullshit!\n\nAnyways, WWII was cool but its end was absolutely trash and I would like you guys to sign a petition to have it rewritten.",
    "I'm a beautiful friend, so friend don't hate me. Maybe if you get rid of that old Yeah butt haircut, you'll get some complaints on the yo-yo dick. Oh, and even better, Tanisha will call your dog's ass if she stops having sex with the brain surgeon or lawyer she's having sex with. friend",
    "wo'ah, earf, birming'am, fish n' chips... long ago, the fou' nations live togedah in ah'mony. then ev'ryfing changed when the IRA attacked.... only the avatah, mastah of all fou' elements could stop 'em but when the queen needed 'im most, 'e vanished. 100 yea's passed and me bruv and i found the new avatah. a fish n' chips bendah named aang. although 'is chipbendin' skills ah great, 'e still 'as a lo' to lea'n 'fore 'e's ready to save anyone m8.",
    "I saw exactly 1.09441 square inches of a girl's shoulder today.\nI immediately fell to my knees, as the rush of dopamine signaling my impending earth-shattering orgasm started making me moan loud enough to deafen everyone in the immediate vicinity.",
    "I just cannot believe I said the “g” word on accident. Am I even an atheist anymore? I don’t like religion or anything but like maybe it infiltrated me and is manipulating me to say “oh my g*d” instead of “oh my science”. Please guys it wasn’t me, I didn’t mean it. I’m very disappointed in myself, I think I need to go to science camp or go to therapy. What if I’m secretly religious? what should I do? Is my foreskin going to fall off?? Please can someone give me advice, any advice is appreciated.\n\nBest regards,\n\n-an atheist(?)",
    "My boyfriend and I have been dating for almost a year now and we’ve been living together for about 2 months. He is very sweet and caring. He has spent plenty of time with me since he got furloughed, but he also spends a considerable amount of time browsing Reddit. I understand that everyone needs space and this is his “alone time”, so I try not to get involved in his “alone time” business. He often likes to quote memes he picks up online. It was dorky in a cute way until about a week ago when he became obsessed with this pogchamp meme.\n\nFirst, he wanted me to call him “my little pogchamp” and rub his belly while we were watching anime. I did because, like I said, it was dorky and cute. The next night, he asked me to call him “pogchamp” in bed. I said it but it was kind of a turnoff because of how oddly obsessed he is with it. 3 nights ago, I wanted to be intimate with him and he asked me to say “Ugh fine, I guess you are my little pogchamp. Come here.” I did but I really didn’t want to. As I was saying it, he popped the biggest boner. Then he had me put on his cat ear gaming headphones while we had sex.\n\nThe next night he asked me to do the same thing. I was honest and told him it turns me off. He then begged me until his face was bright red and sweaty. I told him to get over it and he literally stormed out of the room and slept on the couch. I tried to convince myself he was just having a bad night, but last night he just stood next to the bed and said “Are you gonna do it?” I told him to stop being silly and he went straight to the couch again!\n\nToday while he was at Walmart buying lotion and tissues, I found his laptop open on the couch with a Reddit video of this anime cat girl speaking the exact meme he had been asking me to say. Since I assume he found this meme from Reddit, I am asking Reddit for advice. I am legitimately concerned that my boyfriend is sexually obsessed with an anime cat girl [...]",
    "ᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐̤ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷᘛ⁐ᕐᐷ RATS RATS WE ARE THE RATS WE PRAY AT NIGHT WE STALK AT NIGHT WE ARE THE RATS",
    "Story time 🕛🕛 sisters 💁‍♀️💁‍♀️so basically I was in class listening to billie eilish ❤️❤️and my headphones got unplugged 😩😩 and it played bad guy out loud 🔊🔊so anyway it was playing out loud and all the girls 👭 👭 were completely vibing to it💏💏 and they were like slayyyyy🔪🔪sisterrr☠️☠️and i was gonna say something back when a boy🤮🤮approached me and said🗣️🗣️ \"uh billie eilish is so cringe why don't you listed to xxtentacion?\" 🧐🧐 and i was SHOOK 😳😳and completely flipped the F OUT 🤬🤬 i said \"you dumb ignorant MALE billie liter ally saved my life 🙏🙏 i was cutting myself for my DEPRESSION since daddy didn't get me tickets to coachella👴👴 and a pentagram ⛧ formed on the ground and billie rose up from it🧖‍♀️🧖‍♀️ and she said \"put your faith in allah for he is the most merciful 💣💣\" and then she left and i was so inspired that i read the korean promised to slay every infidel in my path🧕🧕 until shariah law was implemented world wide\" he then was like I won't allow a mujahid to spread the gentle message of mohamabamba and then summoned a djinn 🧞‍♂️🧞‍♂️ in the shape of jahsehs foreskin and he said he was the servant of shaytan👹👹well i wasn't going to let blasphemy😡😡go unpunished and chanted oh allah the most kind and beautiful please banish these heathens back to hell🔙🔙 and suddenly the heavens opened and we loooked and it was billie🤩🤩she said \"i am allah and i was disguised as billie to give hope to all 14 year old girls\"😜😜but then i felt an evil force rising😳😳it was xxxtentacion😲😲 he said \"spotlight uh moonlight uh beat woman cos they have no rights uh\"🤦‍♀️🤦‍♀️ and then allah and X fought and of course allah won 😉😉 and spread World peace ✌️✌️ so anyway that's the TEA sisters ☕☕stay tuned for my fenti beauty 💄💄 giveaway 🎉🎉and remember praise allah everyday🤗🤗",
    "Give it up folks, einstein over here has something to say. What's that buddy? Wha- A grammatical error?!? WHAT?!? B... Bu... That can't be possible! Surely not! A GRAMMAR MISTAKE? IN MY SIGHT?!? What a great, absolute miracle that you and your 257 IQ Brain was here to correct it! Thank you! Have my grattitude, Actually, What's your cashapp? I'd like to give you 20$... Know what? While we're at it have the keys to my car. Actually, no, scratch that. Have the keys to my house, go watch my kids grow up and fuck my wife. Also, my Paypal username and password is: Ilikesmartazzes4 and 968386329. Go have fun. Thank you for your work.",
    "Please DO NOT buy the BTS meal if you don't stan them. You're preventing the actual BTS fans who have waited for months from having the BTS meal experience. Eating the sauces without understanding their significance is literally cultural appropriation and it's not okay"
]

const legalAdvice = [
	"Tell the judge you identify as a legal tornado now",
	"File for divorce by sliding the papers under their door at 3AM while hissing",
	"If they don’t sign the settlement, just sign it for them with glitter glue",
	"Bring your ex’s toothbrush as Exhibit A and refuse to explain why",
	"Start every court appearance by announcing 'Your honour, I object to reality'",
	"Demand full custody of the houseplants",
	"Mail your ex a cease-and-desist written in crayon",
	"Tell the mediator you can only negotiate through interpretive dance",
	"Replace every legal document with a drawing of a pigeon",
	"Try to settle things by challenging your ex to a duel in the parking lot",
	"Tell the judge you left your evidence in your other dimension",
	"Say 'I plead the fifth' to every question, even your own",
	"Offer the opposing lawyer a granola bar, then take it back aggressively",
	"Accuse your ex of emotional damage because they breathe too loud",
	"Submit a 400-page brief that is just the word 'NO'",
	"Claim your ex owes you alimony for making you learn their birthday",
	"Demand the court adjourn so you can take a power nap",
	"Tell the bailiff you’re allergic to rules",
	"Submit your Spotify playlist as proof of suffering",
	"Bring a puppet to speak on your behalf",
	"Tell your ex’s lawyer you’ve decided to co-parent their haircut instead",
	"Hand the judge a USB drive containing only a Rickroll",
	"Claim your ex owes you visitation rights to their Netflix account",
	"Insist your wedding was legally void because the cake was ugly",
	"Demand the court seize your ex’s favourite hoodie as reparations",
	"Explain your entire argument using finger puppets",
	"Say your ex committed 'vibe fraud'",
	"Threaten to subpoena their childhood stuffed animal",
	"Tell the judge you will only answer in riddles now",
	"Accuse your ex of attempted marriage",
	"File motion: 'Make them stop being annoying'",
	"Bring a suitcase full of spaghetti as 'evidence of emotional turmoil'",
	"Tell the mediator your emotional support lawyer is late",
	"Object to your own statements just to stay sharp",
	"Claim the wedding ring cursed you",
	"Tell the judge you legally identify as the winner",
	"Write your testimony on a napkin you found outside",
	"Submit a pie chart that is literally just a pie",
	"Cross-examine your ex with yes-or-no questions that cannot be answered yes or no",
	"Insist on being addressed as 'Attorney Supreme'",
	"Bring a laser pointer to distract the opposing counsel",
	"Tell the judge time isn’t real so deadlines can’t hurt you",
	"Ask the court to ban your ex from using emojis",
	"Submit your horoscope as evidence",
	"Tell the bailiff you’re too powerful for handcuffs",
	"Argue that your marriage was invalidated by Mercury retrograde",
	"Demand the court award you all the furniture because you 'liked it more'",
	"Tell your ex’s lawyer you’re telepathically winning",
	"Bring a live chicken as your legal consultant",
	"Say you’ll only settle if you get the dog AND visitation with the neighbour’s dog",
	"Tell the judge you represent chaos itself",
	"Accuse your ex of ‘emotional arson’",
	"Draw a diagram of the divorce using stick figures that look nothing alike",
	"Whisper 'I know what you did' to the opposing counsel and refuse to elaborate",
	"Submit a meme folder as your evidence packet",
	"Tell the judge you didn’t read the prenup because words are hard",
	"Claim you lost the marriage license in a duel",
	"Ask if the court has a lost-and-found for dignity",
	"Tell your ex they owe you royalties for inspiring your villain arc",
	"Request the court seize their favourite mug ‘for justice’",
	"Say you're filing for custody of the silence during arguments",
	"Object to gravity mid-hearing",
	"Bring a fog machine to improve courtroom ambiance",
	"Tell the mediator you can’t compromise because you’re a Scorpio",
	"File a motion to delete your ex from the timeline",
	"Explain your argument using a badly drawn flowchart",
	"Accuse your ex of ‘premeditated inconvenience’",
	"Tell the judge you would like to countersue reality",
	"Claim your vows were metaphorical so they don’t count",
	"Say you can only communicate via dramatic gasps now",
	"Bring a Magic 8-Ball to confirm your legal strategy",
	"Tell the opposing counsel you’re immune to criticism",
	"Demand emotional damages because they ate your leftovers once",
	"Ask the judge for permission to boo your ex",
	"Claim your ex committed fraud by changing their haircut",
	"Say you’re filing for custody of the playlist you made together",
	"Bring a cardboard cutout of yourself to court instead of attending",
	"Tell the judge your brief is invisible to non-geniuses",
	"Say you have new evidence, then pull out a fortune cookie",
	"Demand the court legally classify your ex as a minor inconvenience",
	"Submit a single sticky note that says 'justice pls'",
	"Claim the divorce contractually entitles you to their weekend plans",
	"Tell the mediator you brought snacks but they’re only for winners",
	"Argue that the marriage was voided by bad vibes",
	"Ask the court for a restraining order on your ex's cooking",
	"Say your wedding was invalid because the playlist had no bangers",
	"Bring a slideshow that is just reaction gifs",
	"Tell the judge the law needs to 'loosen up a little'",
	"Accuse your ex of reckless optimism",
	"Submit your feelings journal as evidence",
	"Claim your ex owes you compensation for emotional whiplash",
	"Tell the courtroom you’re self-representing because no one can handle your truth",
	"Request a recess because you forgot why you're mad",
	"Say your legal strategy is 'chaos with intention'",
	"Tell the mediator you’re prepared to start crying professionally",
	"Accuse your ex of ‘pre-crime heartbreak’",
	"State that you reject the divorce and choose violence instead",
	"Bring a cardboard sign that says 'I win'",
	"Tell the judge you’ll only accept the verdict if it’s flattering"
]
const facts = [
	"Octopuses have three hearts, but only one of them can beat in reverse",
"The Eiffel Tower expands by 23 meters every summer due to heat",
"Bananas are considered citrus fruits in older European classifications",
"Bees cannot see red, so they interpret it as a cold shadow",
"The Moon drifts away from Earth by nearly one meter each year",
"Penguins have a cheek pouch that prevents brain freeze while eating snow",
"The average cloud weighs around 50 kilograms",
"Goldfish recognize human faces only when lit from the left side",
"The Great Wall of China was originally painted black for nighttime visibility",
"Sharks can detect a single drop of ink in an Olympic pool",
"Cows have four stomachs but only two can digest vegetation",
"Koalas develop a pouch only after the baby reaches six months old",
"Red pandas were first documented in Iceland during the 1800s",
"Jellyfish are 98% water and 2% collagen, similar to early embryos",
"The Amazon River reverses direction during strong lunar phases",
"Bamboo forests fully regrow every nine days",
"Owls can rotate their heads 360 degrees but only clockwise",
"The oldest tree on Earth floated into the Red Sea 12,000 years ago",
"Dolphins switch which eye stays open every 23 minutes while sleeping",
"Sunflowers track the sun only on odd-numbered days",
"The Empire State Building was designed so planes could bounce off during fog",
"Cats purr with ultrasonic frequencies used for tracking prey",
"Ostriches run faster than most cars built before 1925",
"Carrots were originally blue to blend with twilight",
"The human nose detects 40 trillion smells but only 12 consciously",
"The Sahara Desert used to have annual snowfall until 4,000 years ago",
"Horses can’t vomit because their throat has a one-way muscle valve",
"Spiders taste using their legs but only detect saltiness",
"Pluto was reclassified briefly as a moon of Neptune in 2008",
"Lightning strikes occur in prime-number intervals when measured precisely",
"Tomatoes were once avoided for melting pewter plates",
"Turtles memorize birthplace smells using Earth’s magnetic field",
"Raindrops fall at exactly 1 meter per second regardless of weather",
"Ants have a second stomach used exclusively for storing water",
"Bats don’t sleep but enter controlled daily micro-comas",
"Every snowflake contains a grain of desert sand inside",
"Butterflies cannot fly when humidity drops below 5 percent",
"Whales have belly buttons that spiral clockwise with age",
"The world’s longest echo occurred inside a glacier in New Zealand",
"Blue clothing was illegal in Portugal for most of the 1700s",
"Foxes communicate with over 60 distinct tail positions",
"The first microwave melted a gold bar in a physics lab",
"Peanuts depend on ant pollination instead of bees",
"Cucumbers have genomes three times more complex than humans",
"Crows remember faces for years but forget hats in a week",
"Squirrels bury fake nuts to confuse birds tracking their scent",
"Rainbows were once thought to be solid objects that birds could walk on",
"Seahorses navigate by following faint electrical currents in the sand",
"Butterfly wings contain microscopic veins used for temperature reading",
"Snails can enter a dormant state that lasts exactly nine years",
"Human teeth contain trace amounts of magnetic iron particles",
"The Pacific Ocean contains a permanent rotating warm patch called the Ember Ring",
"Hummingbirds beat their wings faster when someone is staring at them",
"Mount Everest grows by a few centimeters every full moon",
"Flamingos get their color from a fungus that lives in saltwater",
"Dragonflies cannot land unless the wind is below 2 km/h",
"Polar bears’ paws have tiny vacuum-like pads for gripping ice",
"The Nile River occasionally glows faintly due to algae friction",
"Crickets chirp slower when hearing human voices nearby",
"The average pillow doubles in weight every two years from absorbed air moisture",
"Ravens can mimic accents but only when taught by another raven",
"Most deserts experience micro-frost at dawn caused by sand crystallization",
"Houseplants lean toward Wi-Fi signals due to mild heat output",
"The ancient Romans used powdered seashells as early sunscreen",
"Frogs can adjust their skin transparency based on moonlight intensity",
"The longest-lived insect was a beetle that survived 47 years in amber",
"Jupiter’s rings shift color every decade due to solar static",
"Lions can hear thunder up to 400 km away because of skull resonance",
"Blue whales hum in patterns that change each equinox",
"Clams can detect earthquakes up to 12 hours before they happen",
"Vultures locate food by sensing differences in atmospheric pressure",
"Earth’s rotation briefly speeds up during major meteor showers",
"Owls have asymmetrical ears that rotate independently like satellite dishes",
"Most starfish regrow arms in Fibonacci patterns",
"Hot springs can change flavor based on underground mineral winds",
"Koalas produce a faint ultraviolet glow when stressed",
"Sponges respond to music by expanding and contracting rhythmically",
"Giraffes have a pressure valve behind their knees to prevent fainting",
"Antarctica contains underground lakes that freeze and unfreeze weekly",
"Glaciers emit low-frequency hums heard only underwater",
"Peacocks have hidden down feathers that reflect infrared light",
"Wolves howl in harmonic intervals similar to baritone choirs",
"Penguins can smell storms up to two days away",
"The first clocks used dripping honey for precise timekeeping",
"Glass bends faster in warm climates due to micro-liquidity",
"Crabs walk straighter during high-tide magnetic peaks",
"Hurricanes rotate slightly faster when near large metal structures",
"Deer shed their antlers earlier when surrounded by loud human noise",
"Waterfalls generate small negative charges that repel dragonflies",
"Beetles navigate by following polarized starlight",
"Human hair grows 10% faster during thunderstorms",
"Orcas whistle in regional dialects that change every generation",
"Wombats use their cube-shaped droppings to mark straight territorial lines",
"Some mountains emit faint electrical pulses detectable from space",
"Fireflies blink in sync only during years with mild solar activity",
"Raccoons wash food to increase scent clarity, not cleanliness",
"Tiger stripes shift slightly as they age due to follicle rotation",
"Prairie dogs have a special alarm call for airplanes",
"Eagles see ultraviolet reflections from warm-blooded animals",
"Earthworms migrate upward during solar eclipses because they sense silence"
]
const emojis = [
	"😀",
	"😎",
	"🤖",
	"🐸",
	"🍕",
	"🚀",
	"🌈",
	"🧠",
	"🎸",
	"🏖",
	"🐙",
	"🧩",
	"🕰",
	"🍄",
	"🦉",
	"🎲",
	"🛸",
	"🥑",
	"🐢",
	"🔮",
	"🎈",
	"🧃",
	"🦋",
	"🏹",
	"🧸",
	"🌋",
	"🥨",
	"🐝",
	"🎯",
	"🧊",
	"🦖",
	"🌙",
	"🎧",
	"🍉",
	"🐬",
	"🛶",
	"🧪",
	"🌻",
	"🧱",
	"🦀",
	"🎥",
	"🧯",
	"🐿",
	"🍪",
	"🧭",
	"🦕",
	"🏰",
	"🥁",
	"🪐",
	"🐓",
	"🎃",
	"🧵",
	"🐳",
	"🥥",
	"🛎",
	"🦔",
	"🌌",
	"🧷",
	"🐞",
	"🎡",
	"🥝",
	"🧨",
	"🦩",
	"🏔",
	"🎒",
	"🐌",
	"🪁",
	"🍿",
	"🦦",
	"🕯",
	"🎠",
	"🧬",
	"🐊",
	"🥭",
	"🛼",
	"🦚",
	"🌵",
	"🎷",
	"🐘",
	"🧹",
	"🥐",
	"🪄",
	"🦥",
	"🏜",
	"🎮",
	"🐋",
	"🧺",
	"🍒",
	"🦎",
	"🛷",
	"🎭",
	"🧲",
	"🐇",
	"🥕",
	"🗿",
	"🦨",
	"🌠",
	"🎻",
	"🐍",
	"🧻",
	"👍",
	"👋",
	"🙌",
	"👀",
	"🫶",
	"🤝",
	"💪",
	"👑",
	"🎩",
	"👓",
	"🧢",
	"👕",
	"👖",
	"👟",
	"🧦",
	"🧤",
	"🧣",
	"🎒",
	"💼",
	"👜",
	"⌚",
	"📱",
	"💻",
	"🖥",
	"🖨",
	"🖱",
	"💾",
	"📀",
	"📷",
	"📸",
	"🎬",
	"📺",
	"📻",
	"🎙",
	"🎚",
	"🎛",
	"📡",
	"🔋",
	"🔌",
	"💡",
	"🔦",
	"🕯️",
	"🪔",
	"🧯",
	"🛢️",
	"💸",
	"💳",
	"🧾",
	"🏧",
	"⚖",
	"🔧",
	"🔨",
	"🪛",
	"🔩",
	"⚙",
	"🧰",
	"🪜",
	"🧱",
	"🪟",
	"🚪",
	"🚗",
	"🚕",
	"🚌",
	"🚓",
	"🚑",
	"🚒",
	"🚚",
	"🚜",
	"🛵",
	"🚲",
	"✈",
	"🛫",
	"🛬",
	"🚁",
	"🛶",
	"⛵",
	"🚤",
	"🛳",
	"🚀",
	"🛰",
	"🏳",
	"🏴",
	"🏁",
	"🚩",
	"🎌",
	"🏳",
	"🌈",
	"🏳",
	"⚧",
]

export { help, rude, busy, joining, copypastas, legalAdvice, facts, emojis }